name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libglfw3-dev libgl1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
        mkdir -p include/stb
        curl -L https://raw.githubusercontent.com/nothings/stb/master/stb_image.h -o include/stb/stb_image.h

    - name: Build
      run: make all

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install dependencies
      run: |
        choco install make
        vcpkg install glfw3:x64-windows
        mkdir -Force include/stb
        curl -L https://raw.githubusercontent.com/nothings/stb/master/stb_image.h -o include/stb/stb_image.h

    - name: Build
      shell: bash
      run: |
        export INCLUDE="$VCPKG_INSTALLATION_ROOT/installed/x64-windows/include;$INCLUDE"
        export LIB="$VCPKG_INSTALLATION_ROOT/installed/x64-windows/lib;$LIB"
        make all
